name: flutter_applicatin_fahri
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:                                                                                                                                                                
  uses-material-design: true
  assets:
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
    - images/6.jpg
    - images/7.jpg
    - images/starbucks.jpg
    - images/fahri.r.jpg
    - images/boboy.jpg
    - images/boboy2.png
    - images/boboy3.jpg
    - images/ypc.png
    - images/objek_wisata.jpg
